### ISSUE TITLE
_loaded Breaks Unit Tests

### ISSUE THREAD

**Issue by Florian1990** [griffo-io/ServiceCollection.Extensions.Modules#2]
The commit 290636baaab958406539e9ad040340b8a16a4ac1 introduced the private static field `_loaded`. This field ensures that modules are loaded only once. This is useful in normal operation. However there is no good way to reset the field `_loaded` in case one needs to build multiple sevice collections e. g. for unit tests.

I would suggest to add a public static method that calls `Clear` on `_loaded`.

**Comment by dariogriffo** [comment]
Fixed in [3.0.1](https://github.com/dariogriffo/ServiceCollection.Extensions.Modules/commit/3b982fb9a2b3e21b5c3de2b602ece123f43c4be3)
Nuget available [here](https://www.nuget.org/packages/ServiceCollection.Extensions.Modules/3.0.1)
Added unit tests example [here](https://github.com/dariogriffo/ServiceCollection.Extensions.Modules/blob/3b982fb9a2b3e21b5c3de2b602ece123f43c4be3/tests/ServiceCollection.Extensions.Modules.UnitTests/ModuleExtensionsTests.cs#L77)
